### ISSUE TITLE
"Cannot read property 'length' of undefined" when changing source document

### ISSUE THREAD

**Issue by Simn** [vshaxe/haxe-hxparser#4]
- Have hello world
- Visualize
- nice
- add space in hello world
- not nice

```shell.ts:437 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Function.hxParserVis_VisBase.visArray (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:9114:15)
    at Function.hxParserVis_Vis_$NFile.vis (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:8204:217)
    at Object.print (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:8197:42)
    at Function.hxParserVis_HtmlPrinter.printSyntaxTree (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:8038:51)
    at Function.hxParserVis_HtmlPrinter.print (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:8034:34)
    at Object.rerender (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:7990:34)
    at Object.provideTextDocumentContent (C:\Users\simn\.vscode\extensions\hxparservis\bin\hxparservis.js:7982:16)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:31499
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9460
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5563)```

**Comment by nadako** [comment]
can't reproduce (however the vis only updates for me when i click on it)

**Comment by Simn** [comment]
Huh, I wonder why it's different for me...
